CREATE TABLE `CarsDB` (
  `RowID` int(11) NOT NULL AUTO_INCREMENT,
  `region` text,
  `price` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `manufacturer` text,
  `model` text,
  `condition` text,
  `cylinders` text,
  `fuel` text,
  `odometer` int(11) DEFAULT NULL,
  `title_status` text,
  `transmission` text,
  `VIN` text,
  `drive` text,
  `size` text,
  `type` text,
  `paint_color` text,
  `state` text,
  `posting_date` date DEFAULT NULL,
  PRIMARY KEY (`RowID`),
  UNIQUE KEY `RowID_UNIQUE` (`RowID`),
  KEY `ModelIndex` (`model`(20))
) ENGINE=InnoDB AUTO_INCREMENT=458242 DEFAULT CHARSET=latin1