CREATE TABLE `Owns` (
  `UserID` int(11) NOT NULL,
  `CarID` int(11) NOT NULL,
  `PriceBought` int(11) DEFAULT NULL,
  `DateBought` date DEFAULT NULL,
  PRIMARY KEY (`CarID`,`UserID`),
  UNIQUE KEY `CarID_UNIQUE` (`CarID`),
  KEY `UserID_FK_idx` (`UserID`),
  CONSTRAINT `RowID` FOREIGN KEY (`CarID`) REFERENCES `CarsDB` (`RowID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `UserID_FK` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1
